### PR TITLE
Git Bash on Windows support fixed

### LINKED ISSUE #6: Windows support

### PR DESCRIPTION
**Pull request by offa**
This fixes the failure due to missing `nt` path on Windows Git Bash.

### CODE REVIEW

**Comment by offa** [comment]
Although not directly related to this PR I've fixed two flake8 warnings. The `venv_pack/tests/test_core.py:56:60: W504 line break after binary operator` breaking the CI at the moment is tricky though:

- Unchanged: `W504 line break after binary operator`
- Operator in next line: `W503 line break before binary operator`
- All in one line: `E501 line too long (100 > 90 characters)`

**Comment by jcrist** [comment]
Thanks for the PR.

> It works with the Git Bash and cmd now.

This works with `cmd` now? Have you tried activating a packaged environment on windows? Since `venv-pack` doesn't yet provide a `cmd` script for activating the environment, I'm curious how that would work.

The missing `nt` directory is something we need to add to this package (should go in here: https://github.com/jcrist/venv-pack/tree/master/venv_pack/scripts), not something we're looking for on the system. If you're interested in making this fix, I'd look at the source in CPython, and update their script as needed to work without any embedded absolute paths.

**Comment by jcrist** [comment]
> The venv_pack/tests/test_core.py:56:60: W504 line break after binary operator breaking the CI at the moment is tricky though

Yeah, flake8 changed this behavior in recent versions. I'd just ignore this one in the setup.cfg: https://github.com/jcrist/venv-pack/blob/98d6b4489eb1f2ed234d61fefebce096d7b02d84/setup.cfg#L4-L10

**Comment by offa** [comment]
> This works with cmd now? Have you tried activating a packaged environment on windows? Since venv-pack doesn't yet provide a cmd script for activating the environment, I'm curious how that would work.

I'm using the _Git Bash_ (almost) always instead of the `cmd`, so I'm going to check `cmd` again tomorrow.

The former doesn't use batch scripts to activate the venv; instead it sources the `Scripts/activate` like a non-Windows system.

Since there was no `nt` directory in the `cmd` generated venv, I expected it to not be that important.

**Comment by jcrist** [comment]
Yeah, this should work fine with `git-bash`. If you're only looking for a quick fix (instead of implementing `cmd` scripts for the full fix), I'd just remove the `script_dirs.append('nt')` call entirely. The TODO already marks windows support incomplete (as do our docs), this would at least prevent things from breaking in your case.

**Comment by jcrist** [comment]
To be clear, the `nt` directory is looking for `venv_pack/scripts/nt/`, it's a missing directory in *this* package (that's what the `TODO` was for). Without it, users using `cmd` or `powershell` won't be able to activate a packaged environment.

**Comment by offa** [comment]
I would be great if we can get the Git Bash working soon. At first I removed the `nt` line, but then moved to this patch. I'm still interested in getting the `cmd` to work though.

If that's Ok I'll update my PR:

- Removing the `nt` line (--> at least working git bash, but cmd still broken)
- Adding the todo again
- Removing the _"fixes #..."_ from the PR (it's not fully fixed unfortunately :-( ).
- Continue with cmd on separate PR

**Comment by jcrist** [comment]
That plan sounds good to me.

**Comment by jcrist** [comment]
Thanks!

**Pull request merged**
